/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface TicketingPlatformInterface extends Interface {
    getFunction(nameOrSignature: "eventsById" | "listingsById" | "nextEventId" | "nextListingId" | "ticketEventId" | "ticketUsed" | "version"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'eventsById', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'listingsById', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextEventId', values?: undefined): string;
encodeFunctionData(functionFragment: 'nextListingId', values?: undefined): string;
encodeFunctionData(functionFragment: 'ticketEventId', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'ticketUsed', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'version', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'eventsById', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'listingsById', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextEventId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextListingId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ticketEventId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ticketUsed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'version', data: BytesLike): Result;
  }

  

  export interface TicketingPlatform extends BaseContract {
    
    connect(runner?: ContractRunner | null): TicketingPlatform;
    waitForDeployment(): Promise<this>;

    interface: TicketingPlatformInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    eventsById: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, bigint, bigint, boolean, bigint, bigint, string] & {eventId: bigint, organizer: string, name: string, venue: string, dateTime: bigint, basePrice: bigint, maxSupply: bigint, mintedCount: bigint, resaleEnabled: boolean, maxResalePrice: bigint, royaltyBps: bigint, venueVerifier: string }],
      'view'
    >
    

    
    listingsById: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, string, bigint, boolean] & {listingId: bigint, tokenId: bigint, seller: string, price: bigint, active: boolean }],
      'view'
    >
    

    
    nextEventId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    nextListingId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    ticketEventId: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    ticketUsed: TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    version: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'eventsById'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, bigint, bigint, boolean, bigint, bigint, string] & {eventId: bigint, organizer: string, name: string, venue: string, dateTime: bigint, basePrice: bigint, maxSupply: bigint, mintedCount: bigint, resaleEnabled: boolean, maxResalePrice: bigint, royaltyBps: bigint, venueVerifier: string }],
      'view'
    >;
getFunction(nameOrSignature: 'listingsById'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, string, bigint, boolean] & {listingId: bigint, tokenId: bigint, seller: string, price: bigint, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'nextEventId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'nextListingId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ticketEventId'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ticketUsed'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'version'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }